-- ============================================================
-- Eusta Servicio Técnico - Entrega 1 de Robledo Iván
-- ============================================================

DROP DATABASE IF EXISTS eusta_servicio_tecnico;
CREATE DATABASE eusta_servicio_tecnico;
USE eusta_servicio_tecnico;

-- =========================
-- TABLAS
-- =========================

-- Table: TECNICOS
CREATE TABLE TECNICOS (
    id_tecnico INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(80) NOT NULL,
    apellido VARCHAR(80) NOT NULL,
    email VARCHAR(120) NULL,
    telefono VARCHAR(30) NULL,
    activo BOOL NOT NULL DEFAULT TRUE,
    fecha_alta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TECNICOS PRIMARY KEY (id_tecnico),
    UNIQUE INDEX AK_TECNICOS_EMAIL (email)
);

-- Table: CLIENTES
CREATE TABLE CLIENTES (
    id_cliente INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(80) NOT NULL,
    apellido VARCHAR(80) NOT NULL,
    dni VARCHAR(20) NULL,
    email VARCHAR(120) NULL,
    telefono VARCHAR(30) NULL,
    direccion VARCHAR(200) NULL,
    fecha_alta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (id_cliente),
    UNIQUE INDEX AK_CLIENTES_DNI (dni),
    UNIQUE INDEX AK_CLIENTES_EMAIL (email)
);

-- Table: EQUIPOS
CREATE TABLE EQUIPOS (
    id_equipo INT NOT NULL AUTO_INCREMENT,
    id_cliente INT NOT NULL,
    tipo_equipo VARCHAR(30) NOT NULL,
    marca VARCHAR(60) NULL,
    modelo VARCHAR(60) NULL,
    numero_serie VARCHAR(80) NULL,
    descripcion VARCHAR(255) NULL,
    fecha_alta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EQUIPOS PRIMARY KEY (id_equipo),
    UNIQUE INDEX AK_EQUIPOS_NUMERO_SERIE (numero_serie),
    INDEX IX_EQUIPOS_ID_CLIENTE (id_cliente)
);

-- Table: SERVICIOS
CREATE TABLE SERVICIOS (
    id_servicio INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255) NULL,
    precio_base DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    activo BOOL NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_SERVICIOS PRIMARY KEY (id_servicio),
    UNIQUE INDEX AK_SERVICIOS_NOMBRE (nombre)
);

-- Table: REPUESTOS
CREATE TABLE REPUESTOS (
    id_repuesto INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255) NULL,
    stock INT NOT NULL DEFAULT 0,
    stock_minimo INT NOT NULL DEFAULT 0,
    costo_unitario DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    precio_sugerido DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    activo BOOL NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_REPUESTOS PRIMARY KEY (id_repuesto),
    UNIQUE INDEX AK_REPUESTOS_NOMBRE (nombre)
);

-- Table: ESTADO_ORDEN
CREATE TABLE ESTADO_ORDEN (
    id_estado INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255) NULL,
    orden_visualizacion INT NOT NULL DEFAULT 0,
    activo BOOL NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_ESTADO_ORDEN PRIMARY KEY (id_estado),
    UNIQUE INDEX AK_ESTADO_ORDEN_NOMBRE (nombre)
);

-- Table: ORDEN_TRABAJO
CREATE TABLE ORDEN_TRABAJO (
    id_orden INT NOT NULL AUTO_INCREMENT,
    id_equipo INT NOT NULL,
    id_tecnico INT NOT NULL,
    fecha_ingreso DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    problema_reportado VARCHAR(500) NOT NULL,
    diagnostico VARCHAR(800) NULL,
    observaciones VARCHAR(800) NULL,
    total_estimado DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_final DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    fecha_cierre DATETIME NULL,
    CONSTRAINT PK_ORDEN_TRABAJO PRIMARY KEY (id_orden),
    INDEX IX_ORDEN_TRABAJO_ID_EQUIPO (id_equipo),
    INDEX IX_ORDEN_TRABAJO_ID_TECNICO (id_tecnico),
    INDEX IX_ORDEN_TRABAJO_FECHA_INGRESO (fecha_ingreso)
);

-- Table: ORDEN_SERVICIO
CREATE TABLE ORDEN_SERVICIO (
    id_orden_servicio INT NOT NULL AUTO_INCREMENT,
    id_orden INT NOT NULL,
    id_servicio INT NOT NULL,
    cantidad INT NOT NULL DEFAULT 1,
    precio_unitario DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT PK_ORDEN_SERVICIO PRIMARY KEY (id_orden_servicio),
    UNIQUE INDEX AK_ORDEN_SERVICIO (id_orden, id_servicio),
    INDEX IX_ORDEN_SERVICIO_ID_ORDEN (id_orden),
    INDEX IX_ORDEN_SERVICIO_ID_SERVICIO (id_servicio)
);

-- Table: ORDEN_REPUESTO
CREATE TABLE ORDEN_REPUESTO (
    id_orden_repuesto INT NOT NULL AUTO_INCREMENT,
    id_orden INT NOT NULL,
    id_repuesto INT NOT NULL,
    cantidad INT NOT NULL DEFAULT 1,
    costo_unitario DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    precio_unitario DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    CONSTRAINT PK_ORDEN_REPUESTO PRIMARY KEY (id_orden_repuesto),
    UNIQUE INDEX AK_ORDEN_REPUESTO (id_orden, id_repuesto),
    INDEX IX_ORDEN_REPUESTO_ID_ORDEN (id_orden),
    INDEX IX_ORDEN_REPUESTO_ID_REPUESTO (id_repuesto)
);

-- Table: PAGOS
CREATE TABLE PAGOS (
    id_pago INT NOT NULL AUTO_INCREMENT,
    id_orden INT NOT NULL,
    fecha_pago DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metodo_pago VARCHAR(30) NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    referencia VARCHAR(100) NULL,
    observacion VARCHAR(255) NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (id_pago),
    INDEX IX_PAGOS_ID_ORDEN (id_orden),
    INDEX IX_PAGOS_FECHA_PAGO (fecha_pago)
);

-- Table: ORDEN_ESTADO
CREATE TABLE ORDEN_ESTADO (
    id_orden_estado INT NOT NULL AUTO_INCREMENT,
    id_orden INT NOT NULL,
    id_estado INT NOT NULL,
    fecha_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observacion VARCHAR(255) NULL,
    CONSTRAINT PK_ORDEN_ESTADO PRIMARY KEY (id_orden_estado),
    INDEX IX_ORDEN_ESTADO_ID_ORDEN (id_orden),
    INDEX IX_ORDEN_ESTADO_ID_ESTADO (id_estado),
    INDEX IX_ORDEN_ESTADO_FECHA_HORA (fecha_hora)
);

-- =========================
-- FOREIGN KEYS
-- =========================

ALTER TABLE EQUIPOS ADD CONSTRAINT FK_EQUIPOS_CLIENTES
FOREIGN KEY FK_EQUIPOS_CLIENTES (id_cliente)
    REFERENCES CLIENTES (id_cliente);

ALTER TABLE ORDEN_TRABAJO ADD CONSTRAINT FK_ORDEN_TRABAJO_EQUIPOS
FOREIGN KEY FK_ORDEN_TRABAJO_EQUIPOS (id_equipo)
    REFERENCES EQUIPOS (id_equipo);

ALTER TABLE ORDEN_TRABAJO ADD CONSTRAINT FK_ORDEN_TRABAJO_TECNICOS
FOREIGN KEY FK_ORDEN_TRABAJO_TECNICOS (id_tecnico)
    REFERENCES TECNICOS (id_tecnico);

ALTER TABLE ORDEN_SERVICIO ADD CONSTRAINT FK_ORDEN_SERVICIO_ORDEN_TRABAJO
FOREIGN KEY FK_ORDEN_SERVICIO_ORDEN_TRABAJO (id_orden)
    REFERENCES ORDEN_TRABAJO (id_orden);

ALTER TABLE ORDEN_SERVICIO ADD CONSTRAINT FK_ORDEN_SERVICIO_SERVICIOS
FOREIGN KEY FK_ORDEN_SERVICIO_SERVICIOS (id_servicio)
    REFERENCES SERVICIOS (id_servicio);

ALTER TABLE ORDEN_REPUESTO ADD CONSTRAINT FK_ORDEN_REPUESTO_ORDEN_TRABAJO
FOREIGN KEY FK_ORDEN_REPUESTO_ORDEN_TRABAJO (id_orden)
    REFERENCES ORDEN_TRABAJO (id_orden);

ALTER TABLE ORDEN_REPUESTO ADD CONSTRAINT FK_ORDEN_REPUESTO_REPUESTOS
FOREIGN KEY FK_ORDEN_REPUESTO_REPUESTOS (id_repuesto)
    REFERENCES REPUESTOS (id_repuesto);

ALTER TABLE PAGOS ADD CONSTRAINT FK_PAGOS_ORDEN_TRABAJO
FOREIGN KEY FK_PAGOS_ORDEN_TRABAJO (id_orden)
    REFERENCES ORDEN_TRABAJO (id_orden);

ALTER TABLE ORDEN_ESTADO ADD CONSTRAINT FK_ORDEN_ESTADO_ORDEN_TRABAJO
FOREIGN KEY FK_ORDEN_ESTADO_ORDEN_TRABAJO (id_orden)
    REFERENCES ORDEN_TRABAJO (id_orden);

ALTER TABLE ORDEN_ESTADO ADD CONSTRAINT FK_ORDEN_ESTADO_ESTADO_ORDEN
FOREIGN KEY FK_ORDEN_ESTADO_ESTADO_ORDEN (id_estado)
    REFERENCES ESTADO_ORDEN (id_estado);
    